config/routes.rb
Rails.application.routes.draw do
  get 'pages/contact'

  get 'pages/home'

  resources :users
  resources :bugs
  root 'bugs#index'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
    
    belongs_to :user
    
    validates :title, :description, presence: true
    
    enum issue_type: [:issue, :enhancement, :feature]
    enum priority: [:low, :medium, :high]
    enum status: [:open, :closed, :monitor]
    
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :bugs
    
    validates :first_name, :last_name, :email, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 105},
        uniqueness: { case_sensitive: false },
        format: { with: VALID_EMAIL_REGEX }
    validates :thumbnail, allow_blank: true, format: {with:%r{\.(gif|jpg|png)\Z}i,
        message: 'must be a URL for GIF, JPG or PNG image.'}    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :set_issue_types, :set_priorities, :set_statuses

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
    
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
        user = User.find(bug_params[:user_id])
        @bug.build_user(:id => user.id)
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :issue_type, :priority, :status, :user_id)
    end
    
    def set_issue_types
      @issue_types = Bug.issue_types
    end
    
    def set_priorities
      @priorities = Bug.priorities
    end
    
    def set_statuses
      @statuses = Bug.statuses
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:last_name, :first_name, :email, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= f.label :user_id %><br>
   <%= f.select :user_id, options_for_select(User.all.collect {|a| ["#{a.last_name},
   #{a.first_name}", a.id]},
   selected: (@bug.user ? @bug.user.id : User.first.id)), {} %>
</div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :issue_type %><br>
    <%= f.select :issue_type, options_for_select(@issue_types.collect {|s| [s[0].humanize, s[0]]},
      selected: @bug.status), {} %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select :priority, options_for_select(@priorities.collect {|s| [s[0].humanize, s[0]]},
      selected: @bug.priority), {} %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(@statuses.collect {|s| [s[0].humanize, s[0]]},
      selected: @bug.status), {} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1 class="form_title">Editing Bug</h1>

<%= render 'form' %>

<span class="btn">
    <%= link_to 'Show', @bug %>
</span>
<span class="btn">
    <%= link_to 'Back', bugs_path %>
</span>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="header">Reported Bugs</h1>

<table class="table">
  <thead class="theader">
    <tr>
      <th class="cell">User</th>
      <th class="cell">Title</th>
      <th class="cell">Description</th>
      <th class="cell">Issue type</th>
      <th class="cell">Priority</th>
      <th class="cell">Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td class="cell"><%= (bug.user.first_name + ' ' + bug.user.last_name) %></td>
        <td class="cell"><%= bug.title %></td>
        <td class="cell"><%= bug.description %></td>
        <td class="cell"><%= bug.issue_type %></td>
        <td class="cell"><%= bug.priority %></td>
        <td class="cell"><%= bug.status %></td>
        <td>
          <ul class="table_crud">
            <li><%= link_to 'Show', bug %></li>
            <li><%= link_to 'Edit', edit_bug_path(bug) %></li>
            <li><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<span class="btn">
<%= link_to 'New Bug', new_bug_path %>
</span>

app/views/bugs/new.html.erb
<h1 class="form_title">New Bug</h1>

<%= render 'form' %>

<span class="btn">
    <%= link_to 'Back', bugs_path %>
</span>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card" style="width: 750px">
  <div class="title"><strong>Title: </strong><%= @bug.title %></div>
  <div class="user"><strong>Submitted by: </strong>
    <%= ((@bug.user.first_name + ' ' + @bug.user.last_name) || "NA")%>
  </div>
  <div class="row">
    <div class="description"><strong>Description: </strong>
      <%= @bug.description %>
    </div>
    <ul class="bug_info">
      <li><strong>Issue type: </strong><%= @bug.issue_type %></li>
      <li><strong>Priority: </strong><%= @bug.priority %></li>
      <li><strong>Status: </strong><%= @bug.status %></li>
    </ul>
  </div>
</div>
<br>
<div class="btn_box">
 <span class="btn">
   <%= link_to 'Edit', edit_bug_path(@bug) %>
 </span>
 <span class="btn">
  <%= link_to 'Back', bugs_path %>
 </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="banner">
    <img class="logo" src=<%= asset_path( 'shield-against-bugs.png' ) %>>
     <%= "Bug Squisher!" %>
  </div>
  <div>
    <ul id="menu">
      <li><a href="/pages/home">Home</a></li>
      <li><a href="/bugs">Bugs</a></li>
      <li><a href="/users">Users</a></li>
      <li><a href="/pages/contact">Contact</a></li>
    </ul>
  </div>
  <br>
  <%= yield %>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Contact Info</h1>
<p>Bug Squisher!</p>
<p>1234 This Street</p>
<p>Anywhere, MI 55555</p>
<p>Help@bugsquisher.com</p>

app/views/pages/home.html.erb
<h1>We squish bugs!</h1>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="form_title">Editing User</h1>

<%= render 'form' %>

<span class="btn">
    <%= link_to 'Show', @user %>
</span>
<span class="btn">
    <%= link_to 'Back', users_path %>
</span>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="header">Listing Users</h1>

<table class="table">
  <thead class="theader">
    <tr>
      <th class="cell">User</th>
      <th class="cell">Email</th>
      <th class="cell">Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="cell"><%= user.first_name + ' ' + user.last_name %></td>
        <td class="cell"><%= user.email %></td>
        <td class="cell"><%= user.thumbnail %></td>
        <td>
          <ul class="table_crud">
            <li><%= link_to 'Show', user %></li>
            <li><%= link_to 'Edit', edit_user_path(user) %></li>
            <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<span class="btn">
  <%= link_to 'New User', new_user_path %>
</span>

app/views/users/new.html.erb
<h1 class="form_title">New User</h1>

<%= render 'form' %>

<span class="btn">
    <%= link_to 'Back', users_path %>
</span>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card">
  <img class="user_thumb" alt="user image">
  <p class="user_info"><strong>User: </strong><%= @user.first_name + ' ' + @user.last_name %></p>
  <p class="user_info" style="padding-bottom: 15px"><strong>Email: </strong><%= @user.email %></p>
</div>
 <br>
 <br>
 <span class="btn">
   <%= link_to 'Edit', edit_user_path(@user) %>
 </span>
 <span class="btn">
  <%= link_to 'Back', users_path %>
 </span>